apiVersion: 1

datasources:
  - name: Loan API
    type: json-datasource
    access: proxy
    url: http://prediction-api:8000
    isDefault: true
    jsonData:
      tlsSkipVerify: true
    editable: true
    version: 1
    uid: loan-api
